apiVersion: v1
kind: Pod
metadata:
  name: nginx-webapp
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 8080
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: aws-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: aws-secret
          key: password
  volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "aws-secrets-manager"
