apiVersion: v1
kind: Pod
metadata:
  name: nginx-webapp
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: aws-secret-volume
      mountPath: /etc/myapp
  volumes:
  - name: aws-secret-volume
    persistentVolumeClaim:
      claimName: aws-secret-pvc