apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-secret-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: secrets-manager.csi.k8s.aws