apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  annotations:
    # Annotation to indicate that the secret should be fetched from AWS Secrets Manager
    secretsmanager.amazonaws.com/secret-name: my-aws-secret
    secretsmanager.amazonaws.com/region: us-west-2  # Specify your AWS region here
type: Opaque