apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
     runAsUser: 1000
     runAsGroup: 3000
     readOnlyRootFilesystem: true
     runAsNonRoot: true
     allowPrivilegeEscalation: false
    resources:
     limits:
        memory: "128Mi"
        cpu: "500m" 